services:
  customerservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: ecomcustomerdb
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
